/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @dfinity/caffeine-bindgen@0.1.0-beta.7.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FinancialTransaction {
  'id' : bigint,
  'paymentMethod' : string,
  'orderId' : [] | [bigint],
  'timestamp' : Time,
  'amount' : bigint,
}
export interface InventoryItem {
  'id' : bigint,
  'lowStockThreshold' : bigint,
  'name' : string,
  'quantity' : bigint,
  'supplierId' : [] | [bigint],
}
export interface MenuItem {
  'id' : bigint,
  'name' : string,
  'available' : boolean,
  'category' : string,
  'price' : bigint,
}
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'total' : bigint,
  'tableNumber' : [] | [bigint],
  'timestamp' : Time,
  'waiter' : Principal,
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'quantity' : bigint,
  'price' : bigint,
  'menuItemId' : bigint,
}
export type OrderStatus = { 'preparing' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'served' : null } |
  { 'ready' : null };
export type RestaurantRole = { 'manager' : null } |
  { 'cook' : null } |
  { 'waiter' : null };
export interface Supplier {
  'id' : bigint,
  'contactInfo' : string,
  'name' : string,
}
export interface Table {
  'status' : TableStatus,
  'number' : bigint,
  'capacity' : bigint,
}
export type TableStatus = { 'occupied' : null } |
  { 'reserved' : null } |
  { 'available' : null };
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'restaurantRole' : [] | [RestaurantRole],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  'addInventoryItem' : ActorMethod<[string, [] | [bigint], bigint], bigint>,
  'addMenuItem' : ActorMethod<[string, string, bigint], bigint>,
  'addStaffMember' : ActorMethod<
    [string, RestaurantRole, Principal],
    undefined
  >,
  'addSupplier' : ActorMethod<[string, string], bigint>,
  'addTable' : ActorMethod<[bigint, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrder' : ActorMethod<[[] | [bigint], Array<OrderItem>], bigint>,
  'getAllInventoryItems' : ActorMethod<[], Array<InventoryItem>>,
  'getAllMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllStaffMembers' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getAllSuppliers' : ActorMethod<[], Array<Supplier>>,
  'getAllTables' : ActorMethod<[], Array<Table>>,
  'getAllTransactions' : ActorMethod<[], Array<FinancialTransaction>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInventoryItem' : ActorMethod<[bigint], [] | [InventoryItem]>,
  'getMenuItem' : ActorMethod<[bigint], [] | [MenuItem]>,
  'getOrder' : ActorMethod<[bigint], [] | [Order]>,
  'getSupplier' : ActorMethod<[bigint], [] | [Supplier]>,
  'getTable' : ActorMethod<[bigint], [] | [Table]>,
  'getTransaction' : ActorMethod<[bigint], [] | [FinancialTransaction]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordTransaction' : ActorMethod<[bigint, string, [] | [bigint]], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateInventoryQuantity' : ActorMethod<[bigint, bigint], undefined>,
  'updateMenuItemAvailability' : ActorMethod<[bigint, boolean], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
  'updateStaffMember' : ActorMethod<
    [Principal, string, RestaurantRole],
    undefined
  >,
  'updateTableStatus' : ActorMethod<[bigint, TableStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];