/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @dfinity/caffeine-bindgen@0.1.0-beta.7.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RestaurantRole = IDL.Variant({
  'manager' : IDL.Null,
  'cook' : IDL.Null,
  'waiter' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
  'menuItemId' : IDL.Nat,
});
export const InventoryItem = IDL.Record({
  'id' : IDL.Nat,
  'lowStockThreshold' : IDL.Nat,
  'name' : IDL.Text,
  'quantity' : IDL.Nat,
  'supplierId' : IDL.Opt(IDL.Nat),
});
export const MenuItem = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'available' : IDL.Bool,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const OrderStatus = IDL.Variant({
  'preparing' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'served' : IDL.Null,
  'ready' : IDL.Null,
});
export const Time = IDL.Int;
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'total' : IDL.Nat,
  'tableNumber' : IDL.Opt(IDL.Nat),
  'timestamp' : Time,
  'waiter' : IDL.Principal,
  'items' : IDL.Vec(OrderItem),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'restaurantRole' : IDL.Opt(RestaurantRole),
});
export const Supplier = IDL.Record({
  'id' : IDL.Nat,
  'contactInfo' : IDL.Text,
  'name' : IDL.Text,
});
export const TableStatus = IDL.Variant({
  'occupied' : IDL.Null,
  'reserved' : IDL.Null,
  'available' : IDL.Null,
});
export const Table = IDL.Record({
  'status' : TableStatus,
  'number' : IDL.Nat,
  'capacity' : IDL.Nat,
});
export const FinancialTransaction = IDL.Record({
  'id' : IDL.Nat,
  'paymentMethod' : IDL.Text,
  'orderId' : IDL.Opt(IDL.Nat),
  'timestamp' : Time,
  'amount' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addInventoryItem' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Nat), IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'addMenuItem' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Nat], []),
  'addStaffMember' : IDL.Func(
      [IDL.Text, RestaurantRole, IDL.Principal],
      [],
      [],
    ),
  'addSupplier' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'addTable' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrder' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Vec(OrderItem)],
      [IDL.Nat],
      [],
    ),
  'getAllInventoryItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
  'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllStaffMembers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getAllSuppliers' : IDL.Func([], [IDL.Vec(Supplier)], ['query']),
  'getAllTables' : IDL.Func([], [IDL.Vec(Table)], ['query']),
  'getAllTransactions' : IDL.Func(
      [],
      [IDL.Vec(FinancialTransaction)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInventoryItem' : IDL.Func([IDL.Nat], [IDL.Opt(InventoryItem)], ['query']),
  'getMenuItem' : IDL.Func([IDL.Nat], [IDL.Opt(MenuItem)], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  'getSupplier' : IDL.Func([IDL.Nat], [IDL.Opt(Supplier)], ['query']),
  'getTable' : IDL.Func([IDL.Nat], [IDL.Opt(Table)], ['query']),
  'getTransaction' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(FinancialTransaction)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordTransaction' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Opt(IDL.Nat)],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateInventoryQuantity' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateMenuItemAvailability' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  'updateStaffMember' : IDL.Func(
      [IDL.Principal, IDL.Text, RestaurantRole],
      [],
      [],
    ),
  'updateTableStatus' : IDL.Func([IDL.Nat, TableStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RestaurantRole = IDL.Variant({
    'manager' : IDL.Null,
    'cook' : IDL.Null,
    'waiter' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
    'menuItemId' : IDL.Nat,
  });
  const InventoryItem = IDL.Record({
    'id' : IDL.Nat,
    'lowStockThreshold' : IDL.Nat,
    'name' : IDL.Text,
    'quantity' : IDL.Nat,
    'supplierId' : IDL.Opt(IDL.Nat),
  });
  const MenuItem = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'available' : IDL.Bool,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const OrderStatus = IDL.Variant({
    'preparing' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'served' : IDL.Null,
    'ready' : IDL.Null,
  });
  const Time = IDL.Int;
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'total' : IDL.Nat,
    'tableNumber' : IDL.Opt(IDL.Nat),
    'timestamp' : Time,
    'waiter' : IDL.Principal,
    'items' : IDL.Vec(OrderItem),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'restaurantRole' : IDL.Opt(RestaurantRole),
  });
  const Supplier = IDL.Record({
    'id' : IDL.Nat,
    'contactInfo' : IDL.Text,
    'name' : IDL.Text,
  });
  const TableStatus = IDL.Variant({
    'occupied' : IDL.Null,
    'reserved' : IDL.Null,
    'available' : IDL.Null,
  });
  const Table = IDL.Record({
    'status' : TableStatus,
    'number' : IDL.Nat,
    'capacity' : IDL.Nat,
  });
  const FinancialTransaction = IDL.Record({
    'id' : IDL.Nat,
    'paymentMethod' : IDL.Text,
    'orderId' : IDL.Opt(IDL.Nat),
    'timestamp' : Time,
    'amount' : IDL.Nat,
  });
  
  return IDL.Service({
    'addInventoryItem' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Nat), IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'addMenuItem' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Nat], []),
    'addStaffMember' : IDL.Func(
        [IDL.Text, RestaurantRole, IDL.Principal],
        [],
        [],
      ),
    'addSupplier' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'addTable' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrder' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Vec(OrderItem)],
        [IDL.Nat],
        [],
      ),
    'getAllInventoryItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
    'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllStaffMembers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getAllSuppliers' : IDL.Func([], [IDL.Vec(Supplier)], ['query']),
    'getAllTables' : IDL.Func([], [IDL.Vec(Table)], ['query']),
    'getAllTransactions' : IDL.Func(
        [],
        [IDL.Vec(FinancialTransaction)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInventoryItem' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(InventoryItem)],
        ['query'],
      ),
    'getMenuItem' : IDL.Func([IDL.Nat], [IDL.Opt(MenuItem)], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
    'getSupplier' : IDL.Func([IDL.Nat], [IDL.Opt(Supplier)], ['query']),
    'getTable' : IDL.Func([IDL.Nat], [IDL.Opt(Table)], ['query']),
    'getTransaction' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(FinancialTransaction)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordTransaction' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Opt(IDL.Nat)],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateInventoryQuantity' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateMenuItemAvailability' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
    'updateStaffMember' : IDL.Func(
        [IDL.Principal, IDL.Text, RestaurantRole],
        [],
        [],
      ),
    'updateTableStatus' : IDL.Func([IDL.Nat, TableStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };