/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @dfinity/caffeine-bindgen@0.1.0-beta.7.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface InventoryItem {
    id: bigint;
    lowStockThreshold: bigint;
    name: string;
    quantity: bigint;
    supplierId?: bigint;
}
export interface MenuItem {
    id: bigint;
    name: string;
    available: boolean;
    category: string;
    price: bigint;
}
export type Time = bigint;
export interface Table {
    status: TableStatus;
    number: bigint;
    capacity: bigint;
}
export interface OrderItem {
    quantity: bigint;
    price: bigint;
    menuItemId: bigint;
}
export interface FinancialTransaction {
    id: bigint;
    paymentMethod: string;
    orderId?: bigint;
    timestamp: Time;
    amount: bigint;
}
export interface Supplier {
    id: bigint;
    contactInfo: string;
    name: string;
}
export interface UserProfile {
    name: string;
    restaurantRole?: RestaurantRole;
}
export interface Order {
    id: bigint;
    status: OrderStatus;
    total: bigint;
    tableNumber?: bigint;
    timestamp: Time;
    waiter: Principal;
    items: Array<OrderItem>;
}
export enum OrderStatus {
    preparing = "preparing",
    pending = "pending",
    completed = "completed",
    served = "served",
    ready = "ready"
}
export enum RestaurantRole {
    manager = "manager",
    cook = "cook",
    waiter = "waiter"
}
export enum TableStatus {
    occupied = "occupied",
    reserved = "reserved",
    available = "available"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    addInventoryItem(name: string, supplierId: bigint | null, lowStockThreshold: bigint): Promise<bigint>;
    addMenuItem(name: string, category: string, price: bigint): Promise<bigint>;
    addStaffMember(name: string, role: RestaurantRole, principal: Principal): Promise<void>;
    addSupplier(name: string, contactInfo: string): Promise<bigint>;
    addTable(number: bigint, capacity: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createOrder(tableNumber: bigint | null, items: Array<OrderItem>): Promise<bigint>;
    getAllInventoryItems(): Promise<Array<InventoryItem>>;
    getAllMenuItems(): Promise<Array<MenuItem>>;
    getAllOrders(): Promise<Array<Order>>;
    getAllStaffMembers(): Promise<Array<[Principal, UserProfile]>>;
    getAllSuppliers(): Promise<Array<Supplier>>;
    getAllTables(): Promise<Array<Table>>;
    getAllTransactions(): Promise<Array<FinancialTransaction>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getInventoryItem(inventoryId: bigint): Promise<InventoryItem | null>;
    getMenuItem(menuItemId: bigint): Promise<MenuItem | null>;
    getOrder(orderId: bigint): Promise<Order | null>;
    getSupplier(supplierId: bigint): Promise<Supplier | null>;
    getTable(tableNumber: bigint): Promise<Table | null>;
    getTransaction(transactionId: bigint): Promise<FinancialTransaction | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    recordTransaction(amount: bigint, paymentMethod: string, orderId: bigint | null): Promise<bigint>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateInventoryQuantity(inventoryId: bigint, quantity: bigint): Promise<void>;
    updateMenuItemAvailability(menuItemId: bigint, available: boolean): Promise<void>;
    updateOrderStatus(orderId: bigint, status: OrderStatus): Promise<void>;
    updateStaffMember(principal: Principal, name: string, role: RestaurantRole): Promise<void>;
    updateTableStatus(tableNumber: bigint, status: TableStatus): Promise<void>;
}
import type { FinancialTransaction as _FinancialTransaction, InventoryItem as _InventoryItem, MenuItem as _MenuItem, Order as _Order, OrderItem as _OrderItem, OrderStatus as _OrderStatus, RestaurantRole as _RestaurantRole, Supplier as _Supplier, Table as _Table, TableStatus as _TableStatus, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addInventoryItem(arg0: string, arg1: bigint | null, arg2: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addInventoryItem(arg0, to_candid_opt_n1(this.uploadFile, this.downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInventoryItem(arg0, to_candid_opt_n1(this.uploadFile, this.downloadFile, arg1), arg2);
            return result;
        }
    }
    async addMenuItem(arg0: string, arg1: string, arg2: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addMenuItem(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMenuItem(arg0, arg1, arg2);
            return result;
        }
    }
    async addStaffMember(arg0: string, arg1: RestaurantRole, arg2: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addStaffMember(arg0, to_candid_RestaurantRole_n2(this.uploadFile, this.downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStaffMember(arg0, to_candid_RestaurantRole_n2(this.uploadFile, this.downloadFile, arg1), arg2);
            return result;
        }
    }
    async addSupplier(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addSupplier(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSupplier(arg0, arg1);
            return result;
        }
    }
    async addTable(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTable(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTable(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n4(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n4(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async createOrder(arg0: bigint | null, arg1: Array<OrderItem>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0), arg1);
            return result;
        }
    }
    async getAllInventoryItems(): Promise<Array<InventoryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInventoryItems();
                return from_candid_vec_n6(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInventoryItems();
            return from_candid_vec_n6(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllMenuItems(): Promise<Array<MenuItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMenuItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMenuItems();
            return result;
        }
    }
    async getAllOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders();
                return from_candid_vec_n10(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders();
            return from_candid_vec_n10(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllStaffMembers(): Promise<Array<[Principal, UserProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStaffMembers();
                return from_candid_vec_n15(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStaffMembers();
            return from_candid_vec_n15(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllSuppliers(): Promise<Array<Supplier>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSuppliers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSuppliers();
            return result;
        }
    }
    async getAllTables(): Promise<Array<Table>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTables();
                return from_candid_vec_n22(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTables();
            return from_candid_vec_n22(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllTransactions(): Promise<Array<FinancialTransaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTransactions();
                return from_candid_vec_n27(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTransactions();
            return from_candid_vec_n27(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n30(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n30(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n31(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n31(this.uploadFile, this.downloadFile, result);
        }
    }
    async getInventoryItem(arg0: bigint): Promise<InventoryItem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInventoryItem(arg0);
                return from_candid_opt_n33(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInventoryItem(arg0);
            return from_candid_opt_n33(this.uploadFile, this.downloadFile, result);
        }
    }
    async getMenuItem(arg0: bigint): Promise<MenuItem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMenuItem(arg0);
                return from_candid_opt_n34(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMenuItem(arg0);
            return from_candid_opt_n34(this.uploadFile, this.downloadFile, result);
        }
    }
    async getOrder(arg0: bigint): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n35(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n35(this.uploadFile, this.downloadFile, result);
        }
    }
    async getSupplier(arg0: bigint): Promise<Supplier | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSupplier(arg0);
                return from_candid_opt_n36(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSupplier(arg0);
            return from_candid_opt_n36(this.uploadFile, this.downloadFile, result);
        }
    }
    async getTable(arg0: bigint): Promise<Table | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTable(arg0);
                return from_candid_opt_n37(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTable(arg0);
            return from_candid_opt_n37(this.uploadFile, this.downloadFile, result);
        }
    }
    async getTransaction(arg0: bigint): Promise<FinancialTransaction | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransaction(arg0);
                return from_candid_opt_n38(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransaction(arg0);
            return from_candid_opt_n38(this.uploadFile, this.downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n30(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n30(this.uploadFile, this.downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async recordTransaction(arg0: bigint, arg1: string, arg2: bigint | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.recordTransaction(arg0, arg1, to_candid_opt_n1(this.uploadFile, this.downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordTransaction(arg0, arg1, to_candid_opt_n1(this.uploadFile, this.downloadFile, arg2));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n39(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n39(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async updateInventoryQuantity(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInventoryQuantity(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInventoryQuantity(arg0, arg1);
            return result;
        }
    }
    async updateMenuItemAvailability(arg0: bigint, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMenuItemAvailability(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMenuItemAvailability(arg0, arg1);
            return result;
        }
    }
    async updateOrderStatus(arg0: bigint, arg1: OrderStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n41(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n41(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async updateStaffMember(arg0: Principal, arg1: string, arg2: RestaurantRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStaffMember(arg0, arg1, to_candid_RestaurantRole_n2(this.uploadFile, this.downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStaffMember(arg0, arg1, to_candid_RestaurantRole_n2(this.uploadFile, this.downloadFile, arg2));
            return result;
        }
    }
    async updateTableStatus(arg0: bigint, arg1: TableStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTableStatus(arg0, to_candid_TableStatus_n43(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTableStatus(arg0, to_candid_TableStatus_n43(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_FinancialTransaction_n28(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FinancialTransaction): FinancialTransaction {
    return from_candid_record_n29(uploadFile, downloadFile, value);
}
function from_candid_InventoryItem_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InventoryItem): InventoryItem {
    return from_candid_record_n8(uploadFile, downloadFile, value);
}
function from_candid_OrderStatus_n13(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n14(uploadFile, downloadFile, value);
}
function from_candid_Order_n11(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n12(uploadFile, downloadFile, value);
}
function from_candid_RestaurantRole_n20(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RestaurantRole): RestaurantRole {
    return from_candid_variant_n21(uploadFile, downloadFile, value);
}
function from_candid_TableStatus_n25(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TableStatus): TableStatus {
    return from_candid_variant_n26(uploadFile, downloadFile, value);
}
function from_candid_Table_n23(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Table): Table {
    return from_candid_record_n24(uploadFile, downloadFile, value);
}
function from_candid_UserProfile_n17(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n18(uploadFile, downloadFile, value);
}
function from_candid_UserRole_n31(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n32(uploadFile, downloadFile, value);
}
function from_candid_opt_n19(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RestaurantRole]): RestaurantRole | null {
    return value.length === 0 ? null : from_candid_RestaurantRole_n20(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n30(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n17(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n33(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_InventoryItem]): InventoryItem | null {
    return value.length === 0 ? null : from_candid_InventoryItem_n7(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n34(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MenuItem]): MenuItem | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n11(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n36(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Supplier]): Supplier | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n37(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Table]): Table | null {
    return value.length === 0 ? null : from_candid_Table_n23(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n38(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FinancialTransaction]): FinancialTransaction | null {
    return value.length === 0 ? null : from_candid_FinancialTransaction_n28(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _OrderStatus;
    total: bigint;
    tableNumber: [] | [bigint];
    timestamp: _Time;
    waiter: Principal;
    items: Array<_OrderItem>;
}): {
    id: bigint;
    status: OrderStatus;
    total: bigint;
    tableNumber?: bigint;
    timestamp: Time;
    waiter: Principal;
    items: Array<OrderItem>;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n13(uploadFile, downloadFile, value.status),
        total: value.total,
        tableNumber: record_opt_to_undefined(from_candid_opt_n9(uploadFile, downloadFile, value.tableNumber)),
        timestamp: value.timestamp,
        waiter: value.waiter,
        items: value.items
    };
}
function from_candid_record_n18(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    restaurantRole: [] | [_RestaurantRole];
}): {
    name: string;
    restaurantRole?: RestaurantRole;
} {
    return {
        name: value.name,
        restaurantRole: record_opt_to_undefined(from_candid_opt_n19(uploadFile, downloadFile, value.restaurantRole))
    };
}
function from_candid_record_n24(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _TableStatus;
    number: bigint;
    capacity: bigint;
}): {
    status: TableStatus;
    number: bigint;
    capacity: bigint;
} {
    return {
        status: from_candid_TableStatus_n25(uploadFile, downloadFile, value.status),
        number: value.number,
        capacity: value.capacity
    };
}
function from_candid_record_n29(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    paymentMethod: string;
    orderId: [] | [bigint];
    timestamp: _Time;
    amount: bigint;
}): {
    id: bigint;
    paymentMethod: string;
    orderId?: bigint;
    timestamp: Time;
    amount: bigint;
} {
    return {
        id: value.id,
        paymentMethod: value.paymentMethod,
        orderId: record_opt_to_undefined(from_candid_opt_n9(uploadFile, downloadFile, value.orderId)),
        timestamp: value.timestamp,
        amount: value.amount
    };
}
function from_candid_record_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    lowStockThreshold: bigint;
    name: string;
    quantity: bigint;
    supplierId: [] | [bigint];
}): {
    id: bigint;
    lowStockThreshold: bigint;
    name: string;
    quantity: bigint;
    supplierId?: bigint;
} {
    return {
        id: value.id,
        lowStockThreshold: value.lowStockThreshold,
        name: value.name,
        quantity: value.quantity,
        supplierId: record_opt_to_undefined(from_candid_opt_n9(uploadFile, downloadFile, value.supplierId))
    };
}
function from_candid_tuple_n16(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _UserProfile]): [Principal, UserProfile] {
    return [
        value[0],
        from_candid_UserProfile_n17(uploadFile, downloadFile, value[1])
    ];
}
function from_candid_variant_n14(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    preparing: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    served: null;
} | {
    ready: null;
}): OrderStatus {
    return "preparing" in value ? OrderStatus.preparing : "pending" in value ? OrderStatus.pending : "completed" in value ? OrderStatus.completed : "served" in value ? OrderStatus.served : "ready" in value ? OrderStatus.ready : value;
}
function from_candid_variant_n21(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    manager: null;
} | {
    cook: null;
} | {
    waiter: null;
}): RestaurantRole {
    return "manager" in value ? RestaurantRole.manager : "cook" in value ? RestaurantRole.cook : "waiter" in value ? RestaurantRole.waiter : value;
}
function from_candid_variant_n26(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    occupied: null;
} | {
    reserved: null;
} | {
    available: null;
}): TableStatus {
    return "occupied" in value ? TableStatus.occupied : "reserved" in value ? TableStatus.reserved : "available" in value ? TableStatus.available : value;
}
function from_candid_variant_n32(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n11(uploadFile, downloadFile, x));
}
function from_candid_vec_n15(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _UserProfile]>): Array<[Principal, UserProfile]> {
    return value.map((x)=>from_candid_tuple_n16(uploadFile, downloadFile, x));
}
function from_candid_vec_n22(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Table>): Array<Table> {
    return value.map((x)=>from_candid_Table_n23(uploadFile, downloadFile, x));
}
function from_candid_vec_n27(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FinancialTransaction>): Array<FinancialTransaction> {
    return value.map((x)=>from_candid_FinancialTransaction_n28(uploadFile, downloadFile, x));
}
function from_candid_vec_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InventoryItem>): Array<InventoryItem> {
    return value.map((x)=>from_candid_InventoryItem_n7(uploadFile, downloadFile, x));
}
function to_candid_OrderStatus_n41(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n42(uploadFile, downloadFile, value);
}
function to_candid_RestaurantRole_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RestaurantRole): _RestaurantRole {
    return to_candid_variant_n3(uploadFile, downloadFile, value);
}
function to_candid_TableStatus_n43(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TableStatus): _TableStatus {
    return to_candid_variant_n44(uploadFile, downloadFile, value);
}
function to_candid_UserProfile_n39(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n40(uploadFile, downloadFile, value);
}
function to_candid_UserRole_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n5(uploadFile, downloadFile, value);
}
function to_candid_opt_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n40(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    restaurantRole?: RestaurantRole;
}): {
    name: string;
    restaurantRole: [] | [_RestaurantRole];
} {
    return {
        name: value.name,
        restaurantRole: value.restaurantRole ? candid_some(to_candid_RestaurantRole_n2(uploadFile, downloadFile, value.restaurantRole)) : candid_none()
    };
}
function to_candid_variant_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RestaurantRole): {
    manager: null;
} | {
    cook: null;
} | {
    waiter: null;
} {
    return value == RestaurantRole.manager ? {
        manager: null
    } : value == RestaurantRole.cook ? {
        cook: null
    } : value == RestaurantRole.waiter ? {
        waiter: null
    } : value;
}
function to_candid_variant_n42(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    preparing: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    served: null;
} | {
    ready: null;
} {
    return value == OrderStatus.preparing ? {
        preparing: null
    } : value == OrderStatus.pending ? {
        pending: null
    } : value == OrderStatus.completed ? {
        completed: null
    } : value == OrderStatus.served ? {
        served: null
    } : value == OrderStatus.ready ? {
        ready: null
    } : value;
}
function to_candid_variant_n44(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TableStatus): {
    occupied: null;
} | {
    reserved: null;
} | {
    available: null;
} {
    return value == TableStatus.occupied ? {
        occupied: null
    } : value == TableStatus.reserved ? {
        reserved: null
    } : value == TableStatus.available ? {
        available: null
    } : value;
}
function to_candid_variant_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}